apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-auth
  namespace: raytracer

spec:
  configMapTargetRef:
    - parameter: host
      name: raytracer-config
      key: RABBITMQ_URL

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaler
  namespace: raytracer

spec:
  scaleTargetRef:
    name: worker

  minReplicaCount: 0
  maxReplicaCount: 6
  cooldownPeriod: 5

  triggers:
    - type: rabbitmq
      metadata:
        queueName: render_jobs
        mode: QueueLength
        value: "1"
      authenticationRef:
        name: rabbitmq-auth