apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml

  - postgres.yaml
  - rabbitmq.yaml
  - minio.yaml
  - webapp.yaml
  - worker.yaml
  - keda-rabbitmq.yaml